give @s[name="Arsey RC"] fables_avatars:arsey_rc_head_item
give @s[name="Atlaskes"] fables_avatars:atlaskes_head_item
give @s[name="Bigdog184382"] fables_avatars:bigdog184382_head_item
give @s[name="Calico Jacque"] fables_avatars:calico_jacque_head_item
give @s[name="CDN Hambone"] fables_avatars:cdn_hambone_head_item
give @s[name="Cragola"] fables_avatars:cragola_head_item
give @s[name="Damo8030"] fables_avatars:damo8030_head_item
give @s[name="Darth Angelo"] fables_avatars:darth_angelo_head_item
give @s[name="Dcstar36"] fables_avatars:dcstar36_head_item
give @s[name="DiatomicSloth19"] fables_avatars:diatomicsloth19_head_item
give @s[name="DingoZero"] fables_avatars:dingozero_head_item
give @s[name="EMPRESSTlTAN"] fables_avatars:empresstitan_head_item
give @s[name="FiremanKing 316"] fables_avatars:firemanking_316_head_item
give @s[name="FirstStorm5023"] fables_avatars:firststorm5023_head_item
give @s[name="Fr0mm1"] fables_avatars:fr0mm1_head_item
give @s[name="garthcp"] fables_avatars:garthcp_head_item
give @s[name="hillmanunited"] fables_avatars:hillmanunited_head_item
give @s[name="JangoBritt"] fables_avatars:jangobritt_head_item
give @s[name="JonahMacD"] fables_avatars:jonahmacd_head_item
give @s[name="Kailio 1980"] fables_avatars:kailio_1980_head_item
give @s[name="MastaTony"] fables_avatars:mastatony_head_item
give @s[name="Mids128"] fables_avatars:mids128_head_item
give @s[name="MxChlorine"] fables_avatars:mxchlorine_head_item
give @s[name="Ngarvi"] fables_avatars:ngarvi_head_item
give @s[name="NovaEmcarlo"] fables_avatars:novaemcarlo_head_item
give @s[name="OldCdnGamer"] fables_avatars:oldcdngamer_head_item
give @s[name="Purplelady1022"] fables_avatars:purplelady1022_head_item
give @s[name="Qwikstreet"] fables_avatars:qwikstreet_head_item
give @s[name="Raul Del Fuego"] fables_avatars:raul_del_fuego_head_item
give @s[name="Rezpint"] fables_avatars:rezpint_head_item
give @s[name="SFC Preston"] fables_avatars:sgtpreston2684_head_item
give @s[name="SolarYard1998"] fables_avatars:solaryard1998_head_item
give @s[name="Stesko9190"] fables_avatars:stesko_head_item
give @s[name="TCC_Segrub"] fables_avatars:tcc_segrub_head_item
give @s[name="Tellis042"] fables_avatars:tellis042_head_item
give @s[name="Tonystar73"] fables_avatars:tonystar73_head_item
give @s[name="VVangoWookie"] fables_avatars:vvangowookie_head_item
give @s[name="Wookieswife12"] fables_avatars:wookieswife12_head_item
give @s[name="xCGgamesx"] fables_avatars:xcggamesx_head_item
give @s[name="xRaistin"] fables_avatars:xraistin_head_item
give @s[name="acaito333"] fables_avatars:acaito333_head_item