give @s[name="Atlaskes"] fables_avatars:atlaskes_head_item
give @s[name="Calico Jacque"] fables_avatars:calico_jacque_head_item
give @s[name="Dcstar36"] fables_avatars:dcstar36_head_item
give @s[name="DiatomicSloth19"] fables_avatars:diatomicsloth19_head_item
give @s[name="Fr0mm1"] fables_avatars:fr0mm1_head_item
give @s[name="JangoBritt"] fables_avatars:jangobritt_head_item
give @s[name="Mids128"] fables_avatars:mids128_head_item
give @s[name="Ngarvi"] fables_avatars:ngarvi_head_item
give @s[name="Purplelady1022"] fables_avatars:purplelady1022_head_item
give @s[name="Raul Del Fuego"] fables_avatars:raul_del_fuego_head_item
give @s[name="SFC Preston"] fables_avatars:sgtpreston2684_head_item
give @s[name="SolarYard1998"] fables_avatars:solaryard1998_head_item
give @s[name="TCC_Segrub"] fables_avatars:tcc_segrub_head_item
give @s[name="Tellis042"] fables_avatars:tellis042_head_item
give @s[name="Tonystar73"] fables_avatars:tonystar73_head_item
give @s[name="xRaistin"] fables_avatars:xraistin_head_item
give @s[name="acaito333"] fables_avatars:acaito333_head_item
give @s[name="StarryRose1362"] athos_avatars:starryrose_head_item
give @s[name="FiremanKing 316"] athos_avatars:firemanking_316_head_item

give @s[name="MrsDelFuego"] athos_avatars:mrsdelfuego_head_item
