name: New Test SFTP Deploy

on:
  push:
    branches:
      - Pre-Release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for delta sync to compare commits

      - name: "Deploy via SFTP"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{ vars.TESTFTP_SERVER }}
          remote-port: ${{ vars.TESTFTP_PORT }}
          remote-user: ${{ vars.TESTFTP_USERNAME }}
          remote-password: ${{ secrets.TESTFTP_PASSWORD }}
          remote-path: "/worlds/Fables_Flat"
          sync: "delta"
          sync-delta-excludes: ".lftp_ignore"
