name: Test Server via SFTP
on:
  push:
    branches:
      - Pre-Release
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    timeout-minutes: 600 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: ${{ vars.TESTFTP_SERVER }}
          port: ${{ vars.TESTFTP_PORT }}
          user: ${{ vars.TESTFTP_USERNAME }}
          pass: ${{ secrets.TESTFTP_PASSWORD }}
          # lftp settings
          parallel: 10
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: './resource_packs'
          remoteDir: '/worlds/Fables_Flat/resource_packs'
          reverse: true
          ignoreFile: '.lftp_ignore'
          options: '--verbose'
